<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Schedule>
 */
class ScheduleFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Predefined options
        $names = [
            'Delivery to Client A',
            'Pickup from Supplier B',
            'Weekly Inventory Check',
            'Monthly Equipment Maintenance',
            'Urgent Shipment for Client C',
            'Supply Run for Warehouse D',
            'Client E Delivery Confirmation',
            'Weekly Route Optimization Review',
            'Annual Supplier Contract Negotiation',
            'Return Shipment from Client F',
            'Inventory Audit for Warehouse G',
            'Scheduled Maintenance for Vehicle H',
            'Daily Dispatch Review',
            'Emergency Restock for Client I',
            'Quarterly Business Review Meeting',
            'Load Planning for Client J',
            'New Product Launch Coordination',
            'Safety Compliance Audit',
            'Holiday Shipping Preparation',
            'Supplier Quality Assessment',
            'Client K Inventory Update',
            'Shipment Tracking and Reporting',
            'Monthly Logistics Performance Review',
            'Operational Strategy Planning',
            'Warehouse Staff Training Session',
            'Transport Route Planning for Client L',
            'Stock Replenishment for Client M',
            'Client N Feedback Collection',
            'Shipping Cost Analysis Meeting',
            'Logistics Software Training',
            'Supplier Payment Reconciliation',
            'Client O Contract Renewal',
            'Daily Sales Forecast Meeting',
            'Performance Metrics Analysis',
            'Logistics Risk Management Planning',
            'Sustainability Initiative Review',
            'Equipment Safety Inspection',
            'Return Merchandise Authorization Processing',
            'Weekly Team Standup Meeting',
            'Emergency Protocol Review',
            'Vendor Compliance Check',
            'Seasonal Product Demand Planning',
            'Last-Minute Client P Orders',
            'Client Q Delivery Coordination',
            'Fleet Maintenance Scheduling',
            'Cargo Loading Supervision',
            'Freight Cost Negotiation',
            'Customer Satisfaction Survey Review',
            'Route Efficiency Analysis',
            'Supplier Relationship Management',
            'Inventory Turnover Assessment',
            'Packing Protocol Review',
            'Client R Service Level Agreement Review',
            'Monthly Shipping Rate Negotiations',
            'Order Fulfillment Strategy Meeting',
            'Logistics Data Analysis',
            'Supplier Audit Preparation',
            'Client S Project Kickoff',
            'Daily Operations Check-in',
            'Warehouse Layout Optimization',
            'Transport Insurance Review',
            'Cross-Docking Coordination',
            'Client T Satisfaction Follow-up',
            'Cold Chain Compliance Check',
            'Transport Capacity Planning',
            'Quarterly Financial Review',
            'Returns Processing Optimization',
            'Emergency Response Planning',
            'Daily Inventory Management',
            'Transport Fleet Capacity Review',
            'Supplier Risk Assessment',
            'Client U Engagement Session',
            'Packaging Waste Reduction Strategy',
            'Shipping Label Compliance Review',
            'Performance Benchmarking',
            'Freight Carrier Performance Review',
            'Inventory Shrinkage Investigation',
            'Supplier Diversity Initiative Review',
            'Transportation Expense Tracking',
            'Client V Update Meeting',
            'Supply Chain Resilience Planning',
            'Operational Cost Analysis',
            'Logistics Innovation Workshop',
            'Last-Mile Delivery Planning',
            'Shipment Consolidation Strategy',
            'Client W Issue Resolution',
            'Vendor Selection Process',
            'Inventory Management System Training',
            'Distribution Center Efficiency Review',
            'Shipment Volume Forecasting',
            'Client X Strategic Planning',
            'Environmental Impact Assessment',
            'Freight Rate Benchmarking',
            'Supplier Performance Tracking',
            'Customs Clearance Preparation',
            'Logistics Technology Integration',
            'Client Y Delivery Schedule',
            'Inventory Classification Review',
            'Transportation Policy Review',
            'Freight Claims Processing',
            'Client Z Onboarding Meeting',
            'Logistics Cost Control Meeting',
            'Continuous Improvement Strategy',
            'Supplier Pricing Review',
            'Client A2 Inventory Strategy',
            'Shipping Document Verification',
            'Transport Route Review',
            'Logistics KPI Setting',
            'Client B2 Supply Chain Assessment',
            'Vendor Performance Evaluation',
            'Transportation Network Design',
            'Logistics Outsourcing Evaluation',
            'Seasonal Demand Planning',
            'Client C2 Contract Negotiation',
            'Shipping Compliance Audit',
            'Operational Excellence Initiative',
            'Logistics Budget Planning',
            'Client D2 Delivery Confirmation',
            'Supplier Selection Criteria Review',
            'Warehouse Safety Training',
            'Inventory Accuracy Review',
            'Logistics Customer Experience Improvement',
            'Performance Review for Transportation Team',
            'Supplier Performance Improvement Plan',
            'Logistics Capacity Analysis',
            'Client E2 Issue Resolution',
            'Transportation Risk Mitigation',
            'Inventory Policy Review',
            'Client F2 Delivery Coordination',
            'Logistics Project Management',
            'Sourcing Strategy Meeting',
            'Transport Compliance Training',
            'Supplier Performance Recognition',
            'Client G2 Engagement',
            'Logistics Event Planning',
            'Inventory Management System Upgrade',
            'Client H2 Shipping Instructions',
            'Logistics Data Management',
            'Supplier Payment Processing Review',
            'Client I2 Delivery Confirmation',
        ];

        $descriptions = [
            'Delivering goods to Client A on time.',
            'Pickup scheduled from Supplier B to maintain stock.',
            'Weekly check to ensure inventory accuracy.',
            'Routine maintenance for equipment to prevent downtime.',
            'Urgent shipment required for Client C due to last-minute request.',
            'Restocking Warehouse D with necessary supplies.',
            'Confirming delivery details with Client E.',
            'Reviewing the weekly route for optimization.',
            'Negotiating contracts with suppliers for the upcoming year.',
            'Processing return shipments from Client F.',
            'Conducting an inventory audit at Warehouse G.',
            'Scheduling maintenance for Vehicle H to ensure safety.',
            'Reviewing daily dispatches for efficiency.',
            'Handling an emergency restock for Client I.',
            'Preparing for the quarterly business review meeting.',
            'Planning loads for Client J to optimize space.',
            'Coordinating logistics for a new product launch.',
            'Conducting a safety compliance audit to meet regulations.',
            'Preparing for holiday shipping to meet demand.',
            'Assessing supplier quality to maintain standards.',
            'Updating Client K on inventory levels.',
            'Tracking shipments and providing reports to stakeholders.',
            'Reviewing monthly logistics performance metrics.',
            'Planning operational strategies for next quarter.',
            'Training warehouse staff on new procedures.',
            'Planning transport routes for Client L deliveries.',
            'Restocking supplies for Client M based on demand.',
            'Collecting feedback from Client N on service.',
            'Analyzing shipping costs to improve budget.',
            'Training on logistics software for efficiency.',
            'Reconciling supplier payments to ensure accuracy.',
            'Renewing contracts with Client O for next year.',
            'Forecasting daily sales to adjust logistics plans.',
            'Analyzing performance metrics for logistics efficiency.',
            'Planning logistics risk management strategies.',
            'Reviewing sustainability initiatives within logistics.',
            'Inspecting equipment for safety compliance.',
            'Processing return merchandise authorizations promptly.',
            'Holding weekly team stand-up meetings for alignment.',
            'Reviewing emergency protocols to ensure preparedness.',
            'Conducting vendor compliance checks regularly.',
            'Planning for seasonal product demand fluctuations.',
            'Handling last-minute orders for Client P effectively.',
            'Coordinating deliveries with Client Q for timely service.',
            'Scheduling fleet maintenance to minimize downtime.',
            'Supervising cargo loading to ensure safety.',
            'Negotiating freight costs with carriers for better rates.',
            'Reviewing customer satisfaction survey results.',
            'Analyzing route efficiency to reduce costs.',
            'Managing supplier relationships for long-term success.',
            'Assessing inventory turnover for operational efficiency.',
            'Reviewing packing protocols for improvements.',
            'Reviewing SLAs with Client R to ensure compliance.',
            'Negotiating shipping rates monthly for cost control.',
            'Meeting to strategize order fulfillment processes.',
            'Analyzing logistics data for informed decision-making.',
            'Preparing for supplier audits to ensure compliance.',
            'Kicking off projects with Client S effectively.',
            'Checking in on daily operations for smooth functioning.',
            'Optimizing warehouse layouts for efficiency.',
            'Reviewing transport insurance policies for adequacy.',
            'Coordinating cross-docking operations to minimize handling.',
            'Following up with Client T on satisfaction levels.',
            'Checking cold chain compliance for sensitive shipments.',
            'Planning transport capacity to meet demand peaks.',
            'Reviewing quarterly financials for logistics operations.',
            'Optimizing returns processing for customer satisfaction.',
            'Planning emergency responses to logistical challenges.',
            'Managing daily inventory to meet demand accurately.',
            'Reviewing fleet capacity to meet delivery needs.',
            'Assessing supplier risks to mitigate issues.',
            'Engaging with Client U for long-term partnership.',
            'Reviewing waste reduction strategies in packaging.',
            'Verifying shipping label compliance for accuracy.',
            'Setting performance benchmarks for logistics teams.',
            'Reviewing freight carrier performances regularly.',
            'Investigating inventory shrinkage causes and solutions.',
            'Reviewing supplier diversity initiatives for inclusivity.',
            'Tracking transportation expenses for budget control.',
            'Meeting with Client V to discuss logistics strategies.',
            'Planning for supply chain resilience and continuity.',
            'Analyzing operational costs to identify savings.',
            'Conducting workshops for logistics innovations.',
            'Planning last-mile deliveries for customer satisfaction.',
            'Developing strategies for shipment consolidation.',
            'Resolving issues with Client W promptly.',
            'Selecting vendors based on performance metrics.',
            'Training on inventory management systems for accuracy.',
            'Reviewing distribution center efficiencies regularly.',
            'Forecasting shipment volumes for resource allocation.',
            'Strategizing with Client X for future collaborations.',
            'Assessing environmental impacts of logistics operations.',
            'Benchmarking freight rates against industry standards.',
            'Tracking supplier performances for continuous improvement.',
            'Preparing for customs clearances for international shipments.',
            'Integrating logistics technologies for enhanced efficiency.',
            'Scheduling deliveries with Client Y effectively.',
            'Reviewing inventory classifications for optimization.',
            'Updating transportation policies for compliance.',
            'Processing freight claims to recover losses.',
            'Onboarding Client Z with logistics processes.',
            'Planning logistics budgets for the upcoming period.',
            'Continuously improving logistics strategies.',
            'Reviewing supplier pricing for negotiation opportunities.',
            'Strategizing inventory approaches for Client A2.',
            'Verifying shipping documents for accuracy.',
            'Reviewing transport routes for effectiveness.',
            'Setting logistics KPIs for performance tracking.',
            'Assessing supply chain for Client B2 to enhance operations.',
            'Evaluating vendor performances against standards.',
            'Designing transportation networks for efficiency.',
            'Evaluating logistics outsourcing opportunities.',
            'Planning for seasonal demand fluctuations strategically.',
            'Negotiating contracts with Client C2 for favorable terms.',
            'Auditing shipping compliance to meet regulations.',
            'Initiating operational excellence initiatives in logistics.',
            'Planning logistics budgets for effective cost management.',
            'Confirming delivery details with Client D2.',
            'Reviewing criteria for selecting suppliers effectively.',
            'Training warehouse staff on safety protocols.',
            'Reviewing inventory accuracy to ensure stock levels.',
            'Improving customer experience through logistics strategies.',
            'Conducting performance reviews for the transportation team.',
            'Implementing improvement plans for supplier performance.',
            'Analyzing logistics capacity for future growth.',
            'Resolving issues for Client E2 effectively.',
            'Mitigating risks in transportation for smooth operations.',
            'Reviewing inventory policies for effectiveness.',
            'Coordinating delivery details with Client F2.',
            'Managing logistics projects to meet deadlines.',
            'Meeting to discuss sourcing strategies.',
            'Training staff on transport compliance procedures.',
            'Recognizing supplier performance for motivation.',
            'Engaging with Client G2 for service enhancement.',
            'Planning logistics events for industry networking.',
            'Upgrading inventory management systems for efficiency.',
            'Confirming shipping instructions with Client H2.',
            'Managing logistics data for informed decision-making.',
            'Reviewing supplier payment processing for accuracy.',
            'Confirming delivery details with Client I2.',
        ];

        return [
            'name' => $this->faker->randomElement($names),
            'description' => $this->faker->randomElement($descriptions),
            'due_date' => $this->faker->dateTimeBetween('now', '+1 year'),
            'status' => $this->faker->randomElement(['pending', 'in_progress', 'completed']),
            'priority' => $this->faker->randomElement(['low', 'medium', 'high']),
            'image_path' => $this->faker->imageUrl(),
            'assigned_user_id' => $this->faker->randomElement([1, 2]), // Adjust user IDs as needed
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }
}
