<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Shipment>
 */
class ShipmentFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        // Predefined options for Shipment names and descriptions
        $names = [
            'Client A Shipment',
            'Urgent Delivery for Client B',
            'Scheduled Shipment for Client C',
            'Monthly Supply Shipment for Warehouse D',
            'Emergency Stock Shipment for Client E',
            'Regular Shipment to Client F',
            'Overnight Delivery for Client G',
            'Bulk Order Shipment for Client H',
            'International Shipment for Client I',
            'Final Shipment for Client J',
            'Fragile Goods Delivery to Client K',
            'Temperature-Controlled Shipment for Client L',
            'Hazardous Materials Shipment for Client M',
            'Cross-Border Shipment for Client N',
            'Return Shipment from Client O',
            'Scheduled Replenishment for Client P',
            'Freight Shipment for Client Q',
            'Express Delivery for Client R',
            'Standard Shipment for Client S',
            'Quarterly Bulk Shipment for Client T',
            'Special Request Shipment for Client U',
            'Contract Shipment for Client V',
            'Local Delivery for Client W',
            'Last-Minute Shipment for Client X',
            'Consolidated Shipment for Client Y',
            'Priority Shipment for Client Z',
            'Drop Shipment for Client A1',
            'Rescheduled Shipment for Client B1',
            'Regular Freight for Client C1',
            'Additional Stock Shipment for Client D1',
            'Client E1 Weekly Delivery',
            'Client F1 Monthly Supply',
            'Client G1 Yearly Shipment Review',
            'Seasonal Shipment for Client H1',
            'Direct Shipment to Client I1',
            'Return Logistics for Client J1',
            'Scheduled Review for Client K1',
            'Supply Chain Shipment for Client L1',
            'Quality Assurance Shipment for Client M1',
            'Client N1 Contractual Shipment',
            'Client O1 Damage Claim Shipment',
            'Client P1 Compliance Shipment',
            'Client Q1 Shipment Tracking Review',
            'Client R1 Product Launch Shipment',
            'Client S1 Returns Management Shipment',
            'Client T1 Reorder Shipment',
            'Client U1 Fulfillment Shipment',
            'Client V1 Performance Review Shipment',
            'Client W1 Import Shipment',
            'Client X1 Export Shipment',
            'Client Y1 Special Delivery',
            'Client Z1 Critical Shipment',
            'Client A2 Time-Sensitive Shipment',
            'Client B2 Order Update Shipment',
            'Client C2 New Product Shipment',
            'Client D2 Scheduled Maintenance Shipment',
            'Client E2 Seasonal Shipment',
            'Client F2 Return Shipment',
            'Client G2 Rush Delivery',
            'Client H2 Freight Management Shipment',
            'Client I2 Scheduled Audit Shipment',
            'Client J2 Monthly Inventory Shipment',
            'Client K2 Cost-Effective Shipment',
            'Client L2 Compliance Audit Shipment',
            'Client M2 Emergency Response Shipment',
            'Client N2 Supply Chain Optimization Shipment',
            'Client O2 Risk Management Shipment',
            'Client P2 Logistics Performance Shipment',
            'Client Q2 Shipment Reconciliation',
            'Client R2 International Logistics Shipment',
            'Client S2 Compliance Review Shipment',
            'Client T2 Annual Shipment Review',
            'Client U2 Monthly Performance Shipment',
            'Client V2 Review and Approval Shipment',
            'Client W2 Tracking and Updates Shipment',
            'Client X2 Damage Control Shipment',
            'Client Y2 Timely Delivery Shipment',
            'Client Z2 Urgent Response Shipment',
            'Client A3 Scheduled Follow-up Shipment',
            'Client B3 Quality Check Shipment',
            'Client C3 Monthly Shipping Strategy',
            'Client D3 Client Satisfaction Shipment',
            'Client E3 Performance Metrics Shipment',
            'Client F3 Strategic Planning Shipment',
            'Client G3 Compliance Strategy Shipment',
            'Client H3 Priority Handling Shipment',
            'Client I3 Regular Audit Shipment',
            'Client J3 Safety Compliance Shipment',
            'Client K3 Environmental Impact Shipment',
        ];

        $descriptions = [
            'Shipping goods to Client A as scheduled.',
            'Urgent delivery of supplies needed by Client B.',
            'Scheduled shipment to fulfill Client C’s order.',
            'Monthly supply shipment planned for Warehouse D.',
            'Emergency stock shipment for Client E’s urgent needs.',
            'Regular shipment to ensure Client F’s inventory is maintained.',
            'Overnight delivery of critical items for Client G.',
            'Bulk order shipment to meet Client H’s large demand.',
            'International shipment of goods for Client I.',
            'Final shipment of the contract for Client J.',
            'Delivering fragile goods to Client K with special handling.',
            'Temperature-controlled shipment to ensure product integrity for Client L.',
            'Shipping hazardous materials following safety regulations for Client M.',
            'Cross-border shipment to fulfill Client N’s requirements.',
            'Processing return shipment from Client O for faulty products.',
            'Scheduled replenishment shipment for Client P’s restock needs.',
            'Freight shipment arranged for Client Q’s supply chain.',
            'Express delivery for urgent items needed by Client R.',
            'Standard shipment to meet ongoing demand for Client S.',
            'Quarterly bulk shipment planned for Client T’s inventory needs.',
            'Special request shipment tailored for Client U’s unique needs.',
            'Contract shipment as per the agreement with Client V.',
            'Local delivery of goods for Client W’s convenience.',
            'Handling last-minute shipment requests for Client X.',
            'Consolidated shipment for efficiency for Client Y.',
            'Priority shipment for time-sensitive items for Client Z.',
            'Drop shipment directly to Client A1 to streamline processes.',
            'Rescheduled shipment for Client B1 due to logistics changes.',
            'Regular freight shipment planned for Client C1.',
            'Additional stock shipment for Client D1’s growing demand.',
            'Weekly delivery to Client E1 for regular supplies.',
            'Monthly supply for Client F1 to maintain stock levels.',
            'Annual shipment review for Client G1 to assess needs.',
            'Seasonal shipment adjustments for Client H1’s requirements.',
            'Direct shipment to Client I1 to ensure timely delivery.',
            'Return logistics processing for Client J1’s returns.',
            'Scheduled review of shipments for Client K1’s inventory.',
            'Supply chain shipment coordination for Client L1.',
            'Quality assurance shipment for inspection for Client M1.',
            'Contractual shipment fulfillment for Client N1.',
            'Damage claim shipment processing for Client O1.',
            'Compliance shipment to meet regulatory standards for Client P1.',
            'Shipment tracking review meeting with Client Q1.',
            'New product launch shipment planned for Client R1.',
            'Returns management shipment for Client S1’s returns.',
            'Reorder shipment scheduled for Client T1’s needs.',
            'Fulfillment shipment for Client U1’s orders.',
            'Performance review shipment for Client V1’s evaluations.',
            'Import shipment planned for Client W1’s needs.',
            'Export shipment arranged for Client X1’s international trade.',
            'Critical delivery shipment planned for Client Y1.',
            'Urgent response shipment arranged for Client Z1.',
            'Scheduled follow-up shipment for Client A2.',
            'Quality check shipment for inspection and approval for Client B2.',
            'Monthly shipping strategy meeting for Client C2.',
            'Client satisfaction shipment review for Client D2.',
            'Performance metrics shipment for Client E2’s analysis.',
            'Strategic planning shipment for future needs for Client F2.',
            'Compliance strategy shipment to meet standards for Client G2.',
            'Priority handling shipment for sensitive goods for Client H2.',
            'Regular audit shipment for Client I2’s compliance needs.',
            'Safety compliance shipment for hazardous goods for Client J2.',
            'Environmental impact shipment review for Client K2.',
        ];

        return [
            'name' => $this->faker->randomElement($names),
            'description' => $this->faker->randomElement($descriptions),
            'due_date' => $this->faker->dateTimeBetween('now', '+1 year'),
            'status' => $this->faker->randomElement(['pending', 'in_progress', 'completed']),
            'image_path' => $this->faker->imageUrl(),
            'created_by' => 1,
            'updated_by' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ];
    }
}
